### ISSUE TITLE
Ad didn't skip on YouTube Music my man

### ISSUE THREAD

**Issue by Loading617** [JC-comp/JAdSkip#1]

**Comment by LunCh-CECNL** [comment]
@Loading617 
Thanks for reaching out. Please first check if the extension is running and turned on.
![image](https://github.com/JC-comp/JAdSkip/assets/93692182/c2fad4ff-a4e1-453b-8a7c-bf16a6ead2bc)

If it is running, could you please provide the HTML of the YouTube Music page when encountering ads? Here are the steps:

1. Enter Incognito mode using ctrl+shift+n.
2. Browse to YouTube Music and play a song.
3. Pause the ads when they appear.
4. Open the browser's developer tools using ctrl+shift+I.
5. Right-click on the first HTML element tag and select "Copy" -> "Copy outer HTML".
![image](https://github.com/JC-comp/JAdSkip/assets/93692182/0869a1d4-8510-4da9-982e-fd4fb3f97d48)
6. Paste all the content into a text file and upload it here.

**Comment by JC-comp** [comment]
@Loading617 
Thanks for reaching out. Please first check if the extension is running and turned on.
![image](https://github.com/JC-comp/JAdSkip/assets/93692182/c2fad4ff-a4e1-453b-8a7c-bf16a6ead2bc)

If it is running, could you please provide the HTML of the YouTube Music page when encountering ads? Here are the steps:

1. Enter Incognito mode using ctrl+shift+n.
2. Browse to YouTube Music and play a song.
3. Pause the ads when they appear.
4. Open the browser's developer tools using ctrl+shift+I.
5. Right-click on the first HTML element tag and select "Copy" -> "Copy outer HTML".
![image](https://github.com/JC-comp/JAdSkip/assets/93692182/0869a1d4-8510-4da9-982e-fd4fb3f97d48)
6. Paste all the content into a text file and upload it here.
